main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path(
        "sites/create/",
        views.CreateSiteProxyView.as_view(),
        name="create-site",
    ),
    path(
        "sites/update/<int:pk>",
        views.UpdateSiteProxyView.as_view(),
        name="update-site",
    ),
    path(
        "sites/delete/<int:pk>",
        views.DeleteSiteProxyView.as_view(),
        name="delete-site",
    ),
    path("statistics/", views.ListStatisticView.as_view(), name="statistic"),
    path("<str:proxy_name>/<path:proxy_url>", views.proxy_view, name="proxy"),
]

user/urls.py
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("", views.account, name="profile"),
    path(
        "update/<int:pk>", views.UpdateUserView.as_view(), name="user-update"
    ),
]

vpn_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("profile/", include("user.urls", namespace="user")),
    path("", include("main.urls", namespace="main")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.contrib.auth.models import User
from django.db import models

from vpn_service import settings


class Site(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    name = models.CharField(max_length=63, unique=True)
    url = models.URLField()

    def __str__(self):
        return self.name


class Statistic(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    site = models.ForeignKey(
        Site, related_name="connections", on_delete=models.CASCADE
    )
    page_views = models.PositiveIntegerField(default=0)
    data_sent = models.PositiveIntegerField(default=0)
    data_received = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user}, {self.site}"

user/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def __str__(self):
        return self.username

user/forms.py
from django import forms
from django.contrib.auth import get_user_model

from vpn_service import settings


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Repeat password", widget=forms.PasswordInput
    )

    class Meta:
        model = get_user_model()
        fields = ("username", "first_name", "last_name", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        return cd["password2"]

main/views.py
import os
import shutil

import requests

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic

from main import utils
from main.models import Site, Statistic


class ListStatisticView(LoginRequiredMixin, generic.ListView):
    model = Statistic
    fields = "__all__"
    template_name = "vpn_service/statistic_list.html"
    context_object_name = "statistics"

    def get_queryset(self):
        return Statistic.objects.filter(user=self.request.user)


class CreateSiteProxyView(LoginRequiredMixin, generic.CreateView):
    model = Site
    fields = "__all__"
    success_url = reverse_lazy("main:home")
    template_name = "vpn_service/site_form_create.html"


class UpdateSiteProxyView(LoginRequiredMixin, generic.UpdateView):
    model = Site
    fields = "__all__"
    success_url = reverse_lazy("main:home")
    template_name = "vpn_service/site_form_update.html"


class DeleteSiteProxyView(LoginRequiredMixin, generic.DeleteView):
    model = Site
    fields = "__all__"
    success_url = reverse_lazy("main:home")
    template_name = "vpn_service/site_delete.html"

    def post(self, request, *args, **kwargs):
        site = self.get_object()

        media_folder_path = os.path.join("media", site.name)
        if os.path.exists(media_folder_path):
            shutil.rmtree(media_folder_path)

        static_folder_path = os.path.join("static", site.name)
        if os.path.exists(static_folder_path):
            shutil.rmtree(static_folder_path)

        return super().post(request, *args, **kwargs)


class HomeView(LoginRequiredMixin, generic.ListView):
    template_name = "vpn_service/home.html"
    context_object_name = "sites"
    model = Site
    paginate_by = 15

    def get_queryset(self):
        return Site.objects.filter(user=self.request.user)


@login_required()
def proxy_view(request, proxy_name, proxy_url):
    try:
        proxy = Site.objects.get(name=proxy_name)
    except Site.DoesNotExist:
        return HttpResponse("Not find", status=404)

    response = requests.get(proxy_url)

    bytes_sent = len(request.body) if request.body else 0
    bytes_received = len(response.content)

    base_folder = os.path.join("media/", proxy_name)

    soup = utils.download_page_with_selenium(proxy_url, base_folder, proxy)

    utils.update_statistic(request, proxy, bytes_sent, bytes_received, page_views=1)

    return HttpResponse(str(soup), content_type=response.headers["content-type"])

user/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from user.forms import UserRegistrationForm


def account(request):
    if request.method == "GET":
        user = request.user
        return render(request, "user/account.html", context={"user": user})


class UpdateUserView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    template_name = "user/user_form.html"
    fields = ("first_name", "last_name", "email", "username")
    success_url = reverse_lazy("main:home")


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
            return render(
                request,
                "registration/register_done.html",
                {"new_user": new_user},
            )
    else:
        user_form = UserRegistrationForm()
    return render(
        request, "registration/register.html", {"user_form": user_form}
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>VPNgine</title>
  <link rel="stylesheet" href="{% static 'vnp_css_717/styles.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Black+Ops+One&display=swap" rel="stylesheet">
</head>
<body class="body">
  {% block header %}
    {% include "includes/header.html" %}
  {% endblock %}

  <div class="container-fluid mt-1">
    <div class="row">

      <div class="col-sm-3"></div>

      <div class="col-sm-6">

        {% block content %}
        {% endblock %}

        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}

      </div>

      <div class="col-sm-3"></div>

    </div>
  </div>

</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</html>

templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url "main:home" %}">VPNgine</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link nav-link-a" href="{% url "main:statistic" %}">Statistic</a></li>
        <li class="nav-item"><a class="nav-link nav-link-a" href="{% url "main:create-site" %}">New Proxy</a></li>
        <li class="nav-item"><a class="nav-link nav-link-a" href="{% url 'user:profile' %}">Profile</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link bg-success rounded active nav-link-a" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
        {% else %}
          <li class="nav-item"><a class="nav-link bg-success rounded active nav-link-a" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}
  

templates/user/account.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ user.username }}'s profile</h1>
    {% if user.first_name %}<p>First name: {{ user.first_name }}</p>{% endif %}
    {% if user.last_name %}<p>Last name: {{ user.last_name }}</p>{% endif %}
    {% if user.email %}<p>Email: {{ user.email }}</p>{% endif %}
    <a class="btn btn-primary" href="{% url 'main:home' %}">Cancel</a>
    <a class="btn btn-primary mr-2" href="{% url 'user:user-update' pk=user.pk %}">Update info</a>
{% endblock %}

templates/user/user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>Update profile</h1>
<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

  <input type="submit" value="Submit" class="btn btn-primary">
  <a class="btn btn-primary mr-2" href="{% url 'main:home' %}">Cancel</a>
</form>
{% endblock %}

templates/vpn_service/home.html
{% extends "base.html" %}
{% block content %}
    <h1 class="align-content-center">Your Sites</h1>
    <ul>
        {% if not sites %}<h2>You don't have any websites yet</h2>{% endif %}
        {% for site in sites %}
            <li class="site-item">
                <a class="site-name" href="{% url 'main:proxy' proxy_name=site.name proxy_url=site.url %}">{{ site.name }}</a>
                <a class="btn btn-primary float-right" href="{% url 'main:update-site' pk=site.pk %}">Update</a>
                <a class="btn btn-danger float-right mr-2" href="{% url 'main:delete-site' pk=site.pk %}">Delete</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/vpn_service/site_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete proxy?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'main:home' %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

templates/vpn_service/site_form.html
{% load crispy_forms_filters %}

<h1>Create Site's Proxy</h1>
<form style="margin-bottom: 20px" action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

  <input type="submit" value="Submit" class="btn btn-primary">
  <a class="btn btn-primary" href="{% url 'main:home' %}">Cancel</a>
</form>

templates/vpn_service/site_form_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>Create Site's Proxy</h1>
<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

  <input type="submit" value="Submit" class="btn btn-primary">
  <a class="btn btn-primary mr-2" href="{% url 'main:home' %}">Cancel</a>
</form>
{% endblock %}

templates/vpn_service/site_form_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>Update Site's Proxy</h1>
<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

  <input type="submit" value="Submit" class="btn btn-primary">
  <a class="btn btn-primary mr-2" href="{% url 'main:home' %}">Cancel</a>
</form>
{% endblock %}

templates/vpn_service/statistic_list.html
{% extends "base.html" %}
{% block content %}
    <h1>Your Statistics</h1>
    <table>
        <tr>
            <th> Site</th>
            <th>Page Views</th>
            <th>Data Sent</th>
            <th>Data Received</th>
        </tr>
        {% for stat in statistics %}
            <tr>
                <td>{{ stat.site.name }}</td>
                <td>{{ stat.page_views }}</td>
                <td>{{ stat.data_sent }}</td>
                <td>{{ stat.data_received }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}